### ISSUE TITLE
Experience Replay memory

### ISSUE THREAD

**Issue by isildirik** [golsun/deep-RL-time-series#1]
Just thinking about the memory size... Since you don't seem to reset the memory anywhere (sorry if I missed it), and it's a list, does that mean it's continuously growing during training from episode to episode? Could a sample experience from the memory (for a certain state) belong to episode x, as well as episode x+100?

**Comment by golsun** [comment]
yes, you are right. I didn't limit the memory size (though I should...). and a sample can be drawn from all past episodes uniformly. You are welcome to fix it or explore other sampling strategies!

**Comment by isildirik** [comment]
ok thanks i'll look into it.
